server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.74.87.207:3306/mobile?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    url: jdbc:mysql://localhost:3306/mobile?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 18000000
      connection-test-query: SELECT 1
  mail:
    host: smtp.163.com
    port: 587
    username: comp90018@163.com
    password: YPWUCXDOUUDQASMA
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  redis:
    host: 47.74.87.207
    database: 10
    port: 6379
    password: root1234
  data:
    mongodb:
      uri: mongodb://root:root@47.74.87.207:27017
      database: comp90018
  rabbitmq:
    host: 47.74.87.207
    port: 5672
    username: admin
    password: admin
    virtual-host: mobile

minio:
  endpoint: http://47.74.87.207:9000
  fileHost: http://47.74.87.207:9000
  bucketName: comp90018
  accessKey: root
  secretKey: 12345678
  imgSize: 10240000
  fileSize: 10240000

mybatis:
  type-aliases-package: com.comp90018.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.comp90018.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true