server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
spring:
  #  profiles:
  #    active: dev
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/comp-test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 18000000
      connection-test-query: SELECT 1
  mail:
    host: smtp.163.com
    port: 587
    username: comp90018@163.com
    password: YPWUCXDOUUDQASMA
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  redis:
    host: 180.76.230.251
    database: 10
    port: 6379

mybatis:
  type-aliases-package: com.comp90018.pojo
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.comp90018.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true

